spring:
  application:
    name: user-service

server:
  port: 8010

fcm:
  service-account-file: /var/ledger/serviceAccountKey.json

redis:
  host: redis://localhost:6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka