spring:
  application:
    name: zuul-gateway

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders: Cookie,Set-Cookie
    documentation-service:
      path: /docs/**
      serviceId: documentation-service
    government-service:
      path: /gov/**
      serviceId: government-service

auth:
  server:
    url: http://localhost:8000/oauth/check_token
    clientId: web_client_id
    clientSecret: web_client_secret

logging:
  level:
    org:
      springframework:
        web: TRACE

ribbon:
  ReadTimeout: 60000