spring:
  application:
    name: zuul-gateway

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    user-service:
      path: /user/**
      serviceId: user-service