spring:
  application:
    name: zuul-gateway

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    uri: /api/auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: test

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie