spring:
  application:
    name: auth-service

server:
  port: 8000

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka